export const CLI_OPTION_DEFINITIONS = {
  animationRate: { type: "string", default: "5" },
  artifacts: { type: "string", default: ".flakelab/runs" },
  bad: { type: "string", default: "HEAD" },
  bisectParallelism: { type: "string", default: "2" },
  bisectReport: { type: "string", default: "flakelab.bisect.json" },
  concurrency: { type: "string", default: "1" },
  clockOffsetMs: { type: "string", default: "3600000" },
  cookieName: { type: "string" },
  fault: { type: "string", default: "network-delay" },
  html: { type: "string", default: "flakelab.report.html" },
  json: { type: "boolean", default: false },
  jumpAfterMs: { type: "string", default: "0" },
  locale: { type: "string", default: "fr-FR" },
  maxCost: { type: "string", default: "0.25" },
  maxCopies: { type: "string", default: "4" },
  maxDelay: { type: "string", default: "250" },
  discoveryMaxSeconds: { type: "string", default: "300" },
  maxDuplicateBytes: { type: "string", default: "1024" },
  maxHoldMs: { type: "string", default: "250" },
  maxRemoveBytes: { type: "string", default: "1024" },
  maxStallMs: { type: "string", default: "500" },
  maxExperiments: { type: "string", default: "3" },
  maxSeconds: { type: "string", default: "90" },
  maxSteps: { type: "string", default: "3" },
  maxTrials: { type: "string", default: "12" },
  maxWorkers: { type: "string", default: "4" },
  minRate: { type: "string", default: "0.7" },
  model: { type: "string", default: "qwen/qwen3.8-27b" },
  open: { type: "boolean", default: false },
  output: { type: "string", default: "flakelab.repro.yaml" },
  patch: { type: "string", default: "candidate.diff" },
  pattern: { type: "string", default: "**/api/checkout" },
  proof: { type: "string", default: "flakelab.proof.json" },
  promptCredentials: { type: "boolean", default: false },
  publish: { type: "boolean", default: false },
  report: { type: "string", default: "flakelab.investigation.json" },
  reproducer: { type: "string", default: "flakelab.repro.yaml" },
  resourceType: { type: "string", default: "script" },
  runs: { type: "string", default: "4" },
  seed: { type: "string", default: "1" },
  source: { type: "string", multiple: true, default: [] as string[] },
  startupEvent: { type: "string", default: "dom-content-loaded" },
  storage: { type: "string", default: "local-storage" },
  storageKey: { type: "string" },
  timezone: { type: "string", default: "America/New_York" },
  stallAfterMs: { type: "string", default: "0" },
  trials: { type: "string", default: "4" },
  verbose: { type: "boolean", default: false },
  viewportHeight: { type: "string", default: "667" },
  viewportWidth: { type: "string", default: "375" },
} as const

export function requiredOption<T>(value: T | undefined, name: string): T {
  if (value === undefined) {
    throw new Error(`Internal CLI default is missing for --${name}`)
  }
  return value
}
